model_name: resnet50_v2
RK_device_platform: RK1808
model_framework: mxnet
json_file_path: ./resnet50_v2-symbol.json
params_file_path: ./resnet50_v2-0000.params
quantize: True
dataset: ./dataset.txt

graph:
  in_0:
    shape: 3,224,224
    mean_values: 123.675,116.28,103.53
    std_values: 57.63
    img_type: BGR

configs:
  quantized_dtype: asymmetric_quantized-u8
  quantized_algorithm: normal
  optimization_level: 3
  do_sparse_network: True
