model_name: resnet50_v2
RK_device_platform: RK1808
model_framework: tensorflow
model_file_path: ./frozen_resnet_v2_50.pb
quantize: True
dataset: ./dataset.txt

graph:
  in_0:
    name: input
    shape: 299,299,3
    mean_values: 128
    std_values: 128
    img_type: BGR
  out_0:
    name: resnet_v2_50/predictions/Softmax

configs:
  quantized_dtype: asymmetric_quantized-u8
  quantized_algorithm: normal
  optimization_level: 3
  do_sparse_network: True
